name: ci
on:
  push:
    branches:
      - 'main'
  pull_request: {}


jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run validate script
        run: npm run validate

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
